-- Pubblicazione una tantum di notizie e oroscopo del 16/09/2026.
-- Da eseguire su OGNI database tenant (suncity, sunexp3, sunbookingdb).
-- Dalla prossima volta si usa la pagina Contenuti Report.
-- Ripristino: DELETE FROM beauty_news WHERE scan_batch = '20260916T1200';
--            DELETE FROM oroscopo_settimanale WHERE scan_batch = '20260916T1200';

BEGIN;

INSERT INTO beauty_news (scan_batch, titolo, sintesi, categoria, fonte, url, data_notizia, ordine) VALUES ('20260916T1200', $t$Cosmetica, nel 2026 consumi attesi a 13,1 miliardi (+2,3%)$t$, $t$Alla conferenza di apertura della Milano Beauty Week, Cosmetica Italia ha stimato per il 2026 un fatturato di settore di 18,1 miliardi (+1%) e consumi per 13,1 miliardi (+2,3%). A trainare sono e-commerce (+9%), farmacia (+3,5%) e profumeria (+2%).$t$, 'mercato', $t$Il Dirigente$t$, $t$https://ildirigente.com/cosmetica-italiana-nel-2026-atteso-un-fatturato-da-181-miliardi-di-euro/$t$, DATE '2026-09-16', 0);
INSERT INTO beauty_news (scan_batch, titolo, sintesi, categoria, fonte, url, data_notizia, ordine) VALUES ('20260916T1200', $t$Riforma di estetica e acconciatura: le associazioni sollecitano il Senato$t$, $t$Confartigianato, CNA e Casartigiani chiedono al Senato di approvare il Ddl Ancorotti, che aggiorna la legge 1/1990 per circa 150mila imprese. Prevede sanzioni più dure contro l'abusivismo, il riconoscimento dell'affitto di cabina e delle figure di onicotecnico ed esperto trucco.$t$, 'normativa', $t$Confartigianato Imprese$t$, $t$https://www.confartigianato.it/2026/07/acconciatura-ed-estetica-150mila-imprese-aspettano-la-nuova-legge-appello-al-senato-per-il-via-libera-entro-lestate/$t$, DATE '2026-07-22', 1);
INSERT INTO beauty_news (scan_batch, titolo, sintesi, categoria, fonte, url, data_notizia, ordine) VALUES ('20260916T1200', $t$CCNL estetica, i sindacati chiedono +220 euro e la quattordicesima$t$, $t$Filcams, Fisascat e Uiltucs hanno presentato la piattaforma per il rinnovo del contratto di acconciatura ed estetica, in scadenza il 31 dicembre 2026. Chiedono 220 euro in più al terzo livello, la quattordicesima e formazione continua in orario di lavoro.$t$, 'normativa', $t$Fisascat Cisl$t$, $t$https://fisascat.it/news/acconciatura-estetica-piattaforma-unitaria$t$, DATE '2026-07-17', 2);

INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Ariete', $t$Parti a razzo e l'agenda si riempie prima di mercoledì. Rallenta di mezzo passo: quello che rimandi oggi ti torna venerdì, e venerdì hai già poco spazio.$t$, 0);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Toro', $t$La cliente che cambia idea all'ultimo non ce l'ha con te. Tieni il punto con calma, come sai fare: a fine settimana avrai sistemato tutto senza alzare la voce.$t$, 1);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Gemelli', $t$Il telefono squilla sempre nel momento peggiore, e questa settimana lo farà due volte di fila. Rispondi con calma e richiama dopo: nessuno se n'è mai avuto a male.$t$, 2);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Cancro', $t$Una collega capisce al volo di cosa hai bisogno senza che tu lo dica. Ricambia il favore quando tocca a lei: la giornata pesa meno in due che da sola.$t$, 3);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Leone', $t$Questa settimana ti arriva un complimento vero, di quelli detti sulla porta mentre si esce. Prendilo e tienilo da parte: te lo sei guadagnato lavorando, non per caso.$t$, 4);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Vergine', $t$Il magazzino da riordinare ti pesa da giorni e lo sai. Mezz'ora giovedì e te lo togli dai pensieri per un mese: rimandare ancora ti costa più tempo di quanto ne risparmi.$t$, 5);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Bilancia', $t$Incastrare gli orari di tutte è il tuo talento, ma stavolta qualcuno chiederà un posto che non c'è. Dire di no a un orario non è dire di no a una cliente.$t$, 6);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Scorpione', $t$Arriva in ritardo e vorrebbe comunque tutto. Decidi prima cosa ci sta nel tempo che resta e diglielo subito: mettere le cose in chiaro all'inizio ti salva il pomeriggio.$t$, 7);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Sagittario', $t$Settembre ti ha rimessa in moto e hai voglia di cambiare qualcosa. Parti da una cosa piccola e concreta invece che da dieci: quella piccola la porti a casa davvero.$t$, 8);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Capricorno', $t$Guardi i conti più spesso del solito e fai bene, ma non solo la sera tardi. Un'occhiata a mente fresca la mattina ti dice più di un'ora passata a rimuginare.$t$, 9);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Acquario', $t$Ti viene un'idea per organizzare le giornate in un altro modo. Provala su un giorno solo prima di stravolgere la settimana: se funziona te ne accorgi subito.$t$, 10);
INSERT INTO oroscopo_settimanale (scan_batch, segno, testo, ordine) VALUES ('20260916T1200', 'Pesci', $t$Arrivi a venerdì con le mani stanche e la testa pure. Concediti la pausa vera, quella da seduta: la settimana prossima ti serve tutta l'energia che riesci a tenere da parte.$t$, 11);

COMMIT;
